openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Development servers
  - url: https://task-api-2411.onrender.com
    description: Production server on Render
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
